
ACLOCAL_AMFLAGS = -I m4
AM_CPPFLAGS =

if HAVE_CAPNP
AM_CPPFLAGS += @CAPNP_CFLAGS@ -I$(top_srcdir)/ipc/mining
endif

native_objs :=

if HAVE_X86_SHANI
native_objs += sha256_x86_shani.o
endif
if HAVE_AVX2
native_objs += sha256_code_release/sha256_avx2_rorx2.A
endif
if HAVE_AVX1
native_objs += sha256_code_release/sha256_avx1.A
endif
if HAVE_SSE4
native_objs += sha256_code_release/sha256_sse4.A
endif
if HAVE_ARM_SHA2
native_objs += sha256_arm_shani.o
endif

%.A: %.asm
	yasm -f x64 -f elf64 -X gnu -g dwarf2 -D LINUX -o $@ $<

noinst_LIBRARIES = libckpool.a
libckpool_a_SOURCES = libckpool.c sha2.c sha256_arm_shani.c sha256_code_release
libckpool_a_LIBADD = $(native_objs)

bin_PROGRAMS = ckpool ckpmsg notifier
ckpool_SOURCES = ckpool.c generator.c bitcoin.c stratifier.c connector.c \
		 yyjson.c yyjson_util.c
ckpool_LDADD = libckpool.a @LIBS@ @CAPNP_LIBS@ -lcrypto

if HAVE_CAPNP
ckpool_SOURCES += $(top_srcdir)/ipc/mining/mining_ipc.cpp \
	$(top_srcdir)/ipc/mining/init.capnp.c++ \
	$(top_srcdir)/ipc/mining/mining.capnp.c++ \
	$(top_srcdir)/ipc/mining/common.capnp.c++ \
	$(top_srcdir)/ipc/mining/echo.capnp.c++ \
	$(top_srcdir)/ipc/mining/rpc.capnp.c++ \
	$(top_srcdir)/ipc/mining/mp/proxy.capnp.c++
endif

ckpmsg_SOURCES = ckpmsg.c
ckpmsg_LDADD = libckpool.a

notifier_SOURCES = notifier.c
notifier_LDADD = libckpool.a

install-exec-hook:
	setcap CAP_NET_BIND_SERVICE=+eip $(bindir)/ckpool
	$(LN_S) -f ckpool $(DESTDIR)$(bindir)/ckproxy

uninstall-local:
	rm -f $(bindir)/ckproxy
